import React, { useSate, useContext } from "react";
import { Row, Col, Card } from "antd";
import { Link } from "react-router-dom";
import moment from "moment";
import { useGetNftQuery } from "../services/cryptoNFTAPI";
import { ConnectWalletContext } from "../context/ConnectWalletContext";

const NFTTokens = () => {
  const { connectedAccount } = useContext(ConnectWalletContext);
  //this hook is generated by redux ToolKit and get it under from the services component
  const { data: cryptoNFTList, isFetching } = useGetNftQuery(50);
  //implicitly isFetching props given by the toolKit
  if (isFetching) return "Loading..";
  return (
    <div>
      {connectedAccount.length > 0 ? (
        <>
          {cryptoNFTList !== undefined ? (
            <>
              <div>
                <h1 className="crypto-heading-container">List of NFT tokens</h1>
              </div>
              <Row gutter={[32, 32]} className="crypto-card-container">
                {cryptoNFTList?.bundles.length > 0 ||
                cryptoNFTList?.bundles?.asset_contract.length > 0 ? (
                  <>
                    {cryptoNFTList?.bundles.map((nftItems, index) => (
                      <Col
                        xs={24}
                        sm={12}
                        lg={6}
                        className="crypto-card"
                        key={index}
                      >
                        <a
                          href={nftItems.permalink}
                          target="_blank"
                          rel="noreferrer"
                        >
                          <Card
                            style={{
                              width: "100%",
                              height: "100%",
                              borderBlockColor: "cyan",
                            }}
                            title={`${nftItems?.asset_contract?.name ?? ""} `}
                            hoverable
                          >
                            <img
                              style={{
                                marginLeft: "1rem",
                                height: "10rem",
                                width: "10rem",
                                marginBottom: "1rem",
                              }}
                              src={`${
                                nftItems?.asset_contract?.image_url ?? ""
                              }`}
                              alt=""
                            />

                            <h3>
                              <u>Sell order</u>
                            </h3>
                            <p>
                              Symbol: {nftItems?.asset_contract?.symbol ?? ""}
                            </p>
                            <p>
                              Description:{" "}
                              {nftItems?.asset_contract?.description?.length >
                              50
                                ? `${nftItems?.asset_contract?.description?.substring(
                                    0,
                                    50
                                  )},.`
                                : nftItems?.asset_contract?.description}
                            </p>
                            {nftItems.sell_orders.length > 0 ? (
                              <>
                                <p className="current-price">
                                  Base Price:{" "}
                                  {nftItems.sell_orders[0].current_price /
                                    10 ** 18}
                                </p>
                                <p>
                                  CreateDate:{" "}
                                  {moment(
                                    nftItems.sell_orders[0].created_date
                                  ).format("MM/DD/YYYY")}
                                </p>
                                <p>
                                  ClosingDate:{" "}
                                  {moment(
                                    nftItems.sell_orders[0].closing_date
                                  ).format("MM/DD/YYYY")}
                                </p>
                              </>
                            ) : (
                              <>
                                CreateDate:{" "}
                                {moment(
                                  nftItems?.asset_contract?.created_date
                                ).format("MM/DD/YYYY")}
                              </>
                            )}
                          </Card>
                        </a>
                      </Col>
                    ))}
                  </>
                ) : (
                  ""
                )}
              </Row>
            </>
          ) : (
            ""
          )}
        </>
      ) : (
        ""
      )}
    </div>
  );
};

export default NFTTokens;
